name: NodeJS Organization Starter Workflow
on:
  push:
    branches: [ $default_branch ]
  pull_request:
    branches: [ $default_branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout # download repo
        uses: actions/checkout@v4 

      - name: Setup Node
        uses: actions/setup-node@v4 # install node
        with:
          node-version: '20.x'
      
      - name: Install dependencies # install dependecies
        run: npm install

      - name: Run Tests # run the unit tests
        run:  npm test --if-present
      
      - name: Run Coverage
        run: npm run coverage --if-present